support sugest.buildAll and add a plugin to execute queries without waiting for Solr's response
solariumphp/solarium pull request #1119
Opened 2024-01-03 13:18 UTC by mkalkbrenner

2024-01-03 13:19 UTC, mkalkbrenner commented
@thomascorthals documentation needs to be added if accepted

2024-01-04 09:54 UTC, thomascorthals requested changes
Not sure about the use of `TimeoutAwareInterface::MINIMUM_TIMEOUT`.

From <https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html>:

> With [CURLOPT_CONNECTTIMEOUT](https://curl.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html) set to 4 and [CURLOPT_TIMEOUT](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html) set to 2, the operation can never last longer than 2 seconds.

If the adapter is also ConnectionTimeoutAware, the plugin should add that timeout to `MINIMUM_TIMEOUT` I think.

2024-01-05 13:07 UTC, mkalkbrenner commented on src/Core/Client/Adapter/TimeoutAwareInterface.php
> +     * Minimum timeout that should be respected by adapters implementing this interface.
I changed it to FAST_TIMEOUT

2024-01-05 13:12 UTC, mkalkbrenner commented
@thomascorthals thanks for your review. I modified the code and added some minimal documentation.

2024-01-05 13:47 UTC, thomascorthals commented
It still doesn't take the connection timeout into account in the plugin. I wrote this example (I'll commit the cleaned up version afterwards).

```php
<?php

require_once __DIR__.'/init.php';
htmlHeader();

// set a long connection timeout
$adapter->setConnectionTimeout(10);

// connect to a host that will never complete the connection
$config['endpoint']['localhost']['host'] = '10.0.0.0';

// create a client instance
$client = new Solarium\Client($adapter, $eventDispatcher, $config);

// get a suggester query instance and add setting to build all suggesters
$suggester = $client->createSuggester();
$suggester->setBuildAll(true);

// don't wait unitl all suggesters have been built
$client->getPlugin('nowaitforresponserequest');

// this executes the query
$client->suggester($suggester);

htmlFooter();
```

When I comment out the plugin, this results in:
> Solr HTTP error: HTTP request failed, Connection timeout after 10005 ms

With the plugin, this script ends after 1 second. If I `echo $e->getMessage()` in the plugin's `catch` block, I get:
> Solr HTTP error: HTTP request failed, Connection timed out after 1004 milliseconds

That should also be slightly above 10000 milliseconds.

And if I run it on `localhost` against `ncat -k -l 8983` (a listener that never responds), that should actually be slightly above 11000 milliseconds.

2024-01-05 13:54 UTC, thomascorthals commented on src/Plugin/NoWaitForResponseRequest.php
> +                $fastTimeout += $this->client->getAdapter()->getConnectionTimeout() ?? 0;
This hinges on the assumption that all ConnectionTimeoutAware adapters will behave like Curl in this regard.

2024-01-05 14:06 UTC, thomascorthals commented
@mkalkbrenner Actually, we only want to return a `HTTP/1.0 200 OK` response for an operation timeout! A connection timeout should still throw an exception because in that case the request never went through and there is no way of telling with the current plugin implementation.

2024-01-05 14:35 UTC, mkalkbrenner commented
> @mkalkbrenner Actually, we only want to return a `HTTP/1.0 200 OK` response for an operation timeout! A connection timeout should still throw an exception because in that case the request never went through and there is no way of telling with the current plugin implementation.

@thomascorthals I just implemented that right before you posted this comment :-)
But I had to resolve the conflicts first.

2024-01-05 14:58 UTC, thomascorthals commented on src/Plugin/NoWaitForResponseRequest.php
> +        $microtime1 = microtime();
I think this should be `microtime(true)`.

E.g. https://onlinephp.io?s=s7EvyCjg5eLlKkssik8pzS3QUCnJzE01VLBVyM1MLsoHcTQ0Na2RFaRhqigpKk0Fq-LlKs5JTS3QMIFw4JqQDFPQVYDYgWIqmlkgRWlQVQA%2C&v=8.2.13

```php
<?php

var_dump($time1 = microtime());
var_dump($ftime1 = microtime(true));

sleep(4);

var_dump(microtime() - $time1);
var_dump(microtime(true) - $ftime1);
```

```
string(21) "0.33706600 1704466431"
float(1704466431.337109)

Warning: A non-numeric value encountered in /home/user/scripts/code.php on line 8

Warning: A non-numeric value encountered in /home/user/scripts/code.php on line 8
float(0.00018300000000004424)
float(4.000219821929932)
```

2024-01-05 15:22 UTC, mkalkbrenner commented
@thomascorthals I assume it is finished now.

2024-01-05 16:00 UTC, mkalkbrenner commented
Now the failing tests proven that exceptions ar thrown ;-)

2024-01-05 16:28 UTC, mkalkbrenner commented
@thomascorthals Now that the test are passing, should we merge this one and got for a release to fix the documentation?

2024-01-05 21:18 UTC, thomascorthals commented
> @thomascorthals Now that the test are passing, should we merge this one and got for a release to fix the documentation?

@mkalkbrenner Go for it!

2024-01-05 21:19 UTC, thomascorthals submitted a review, later dismissed

2024-01-10 08:27 UTC, merged