Correctly handle nested child documents
solariumphp/solarium pull request #994
Opened 2022-04-28 12:00 UTC by thomascorthals

Fixes #992.

There is no such thing as a "single nested document" in Solr. It always expects an "array of child documents", JSONly speaking. An array is now always created as soon as you add the first child document (as opposed to other single values that only get converted to a multivalue when adding more than one) so the internal data structure always reflects a valid Solr data structure.

Unit and integration tests have been expanded to cover the possible ways to add/set child documents. Documentation including an example has been added.

It is possible to pass a single nested document through `__construct()` or `setFields()`, but I've omitted that from the documentation because it is "un-Solr" syntax.

Moved the control character filtering to the request builder because it's XML specific. It didn't really belong in `Document` anyway and it made things more complicated there. I no longer see a use case for disabling it now that it is in the right place. It is still possible to override if you really want.

```php
use Solarium\Core\Query\Helper;
use Solarium\Core\Query\RequestBuilderInterface;
use Solarium\QueryType\Update\Query\Query as UpdateQuery;
use Solarium\QueryType\Update\RequestBuilder as UpdateRequestBuilder;

$update = new NonControlCharFilteringUpdateQuery();
$doc = $update->createDocument($data);
$update->addDocument($doc);

// and here you'll get HttpException if $data contains control characters
$client->update($update);

class NonControlCharFilteringHelper extends Helper
{
    public function filterControlCharacters(string $data): string
    {
        return $data;
    }
}

class NonControlCharFilteringUpdateQuery extends UpdateQuery
{
    /**
     * Get a requestbuilder that doesn't filter control characters.
     *
     * @return UpdateRequestBuilder
     */
    public function getRequestBuilder(): RequestBuilderInterface
    {
        return new NonControlCharFilteringUpdateRequestBuilder();
    }
}

class NonControlCharFilteringUpdateRequestBuilder extends UpdateRequestBuilder
{
    /**
     * Get a custom helper instance that doesn't filter control characters.
     *
     * @return Helper
     */
    public function getHelper(): Helper
    {
        if (null === $this->helper) {
            $this->helper = new NonControlCharFilteringHelper();
        }

        return $this->helper;
    }
}
```

2022-04-28 17:22 UTC, thomascorthals commented
> There is no such thing as a "single nested document" in Solr. It always expects an "array of child documents", JSONly speaking.

At least that's what the ref guide led me to believe. But it actually works when you do it in JSON.

But I can't figure out how to it in XML.

2022-05-09 12:46 UTC, thomascorthals commented
> I ask myself if we should switch to JSON entirely when sending docs to Solr. XML is from the early days and we never changed it as it is still supported.

I have been wondering the same thing. But for now, I've focused on fixing `Document`.

I've raised [SOLR-16183](https://issues.apache.org/jira/browse/SOLR-16183) for the XML limitation and listed it as a known limitation for now in the docs.

2022-06-08 16:57 UTC, thomascorthals commented
Codecov keeps complaining because I've removed more covered code than I've added so the overall coverage is down by the net difference in total lines. That shouldn't really count as a failure if the diff coverage is 100% imho.

2022-07-01 10:48 UTC, mkalkbrenner requested changes

2022-07-01 10:48 UTC, mkalkbrenner commented on CHANGELOG.md
> +- Adding nested child documents through `Document::setField()` and `Document::addField()`
Needs to be moved

2022-07-01 10:48 UTC, mkalkbrenner commented on CHANGELOG.md
> +- Solarium\QueryType\Update\Query\Document::setFilterControlCharacters(), extend Update\Query\Query to use a custom request builder & helper if you don't want control characters filtered
Needs to be moved

2022-07-04 07:44 UTC, merged